name: Deploy to Cloud Run
on:
 push:
 branches:
 - main
jobs:
 deploy:
 runs-on: ubuntu-latest
steps:
 - name: Checkout code
 uses: actions/checkout@v2
- name: Set up Google Cloud SDK
 uses: google-github-actions/setup-gcloud@master
 with:
 service_account_key: ${{ secrets.GCP_SA_KEY }}
 project_id: ${{ secrets.vital-petal-409810 }}
 export_default_credentials: true
- name: Build and push Docker image
 run: |
 docker build -t gcr.io/${{ secrets.vital-petal-409810 }}/gitactions-terraform-app .
 docker push gcr.io/${{ secrets.vital-petal-409810 }}/gitactions-terraform-app
- name: Deploy to Cloud Run
 run: |
 gcloud run deploy gitactions-terraform-app \
  --image gcr.io/${{ secrets.vital-petal-409810 }}/gitactions-terraform-app \
  --region us-central1 \
  --platform managed