name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate with gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          #workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'github-actions@vital-petal-409810.iam.gserviceaccount.com'
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/gitactions-terraform-app .
      
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-west2-docker.pkg.dev --quiet

      - name: push Docker image
        env:
          GIT_TAG: v0.1.0
        run: |
          
          docker tag $IMAGE_NAME:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/gitactions-terraform-app:$GIT_TAG
    
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/gitactions-terraform-app:$GIT_TAG
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gitactions-terraform-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gitactions-terraform-app:$GIT_TAG \
            --region us-central1 \
            --platform managed
